# Generated by Django 6.1.1 on 2026-09-28 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('x_ft', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('y_ft', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('width_ft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('length_ft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='garden.layout')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('spacing_inches', models.PositiveSmallIntegerField(help_text='In-row spacing between plants (inches).')),
                ('row_spacing_inches', models.PositiveSmallIntegerField(default=18, help_text='Spacing between rows (inches).')),
                ('days_to_maturity_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_to_maturity_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sun_needs', models.CharField(choices=[('full', 'Full sun'), ('partial', 'Partial sun'), ('shade', 'Shade tolerant')], default='full', max_length=20)),
                ('how_to', models.TextField(help_text='Full-sentence growing guidance.')),
                ('citations', models.JSONField(default=list, help_text='List of {title, url, org} citation dicts.')),
                ('antagonists', models.ManyToManyField(blank=True, related_name='antagonist_of', to='garden.plant')),
                ('companions', models.ManyToManyField(blank=True, related_name='companion_of', to='garden.plant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_ft', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('y_ft', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='garden.bed')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='garden.plant')),
            ],
            options={
                'ordering': ['plant__name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('width_ft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('length_ft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='layout',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layouts', to='garden.plot'),
        ),
    ]
