# Generated by Django 6.1.1 on 2026-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, help_text='Relative static path, e.g. images/plants/tomato.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_credit',
            field=models.JSONField(blank=True, default=dict, help_text='Attribution: {creator, license, license_url, source_url, title}.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='varieties',
            field=models.JSONField(blank=True, default=list, help_text='Popular cultivars: list of {name, notes?}.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='varieties_source',
            field=models.JSONField(blank=True, default=dict, help_text='Optional {title, org, url, note} for variety list provenance.'),
        ),
    ]
